# Generated by Django 4.2.30 on 2026-05-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(help_text='One-sentence summary shown on the projects grid.', max_length=300)),
                ('project_type', models.CharField(choices=[('chatbot', 'Chatbot'), ('workflow', 'Workflow'), ('code', 'Code / Script'), ('video', 'Video'), ('web_app', 'Web Application')], max_length=20)),
                ('business_problem', models.TextField()),
                ('tools_used', models.TextField(help_text='One tool per line.')),
                ('key_features', models.TextField(help_text='One feature per line.')),
                ('my_role', models.TextField()),
                ('biggest_challenge', models.TextField()),
                ('what_i_learned', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for iframe embed.')),
                ('downloadable_file', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('github_link', models.URLField(blank=True)),
                ('live_demo_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. Programming Languages, AI/ML, Frameworks, Tools', max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
