# Generated by Django 4.2.30 on 2026-05-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(help_text='e.g. Technical Skills, Soft Skills', max_length=100),
        ),
    ]
